# Generated by Django 2.2.4 on 2019-08-06 10:00

from django.db import migrations, models
import users.func


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employeeId',
            field=models.CharField(error_messages={'unique': 'A user with that employee id already exists.'}, help_text='Required. 50 characters or fewer. number only.', max_length=50, unique=True, validators=[users.func.EmployeeIdValidator()], verbose_name='工号'),
        ),
    ]
