# Generated by Django 2.2.4 on 2019-08-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='题型大类')),
            ],
            options={
                'verbose_name': '题型大类',
                'verbose_name_plural': '题型大类',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='题型小类')),
                ('topic_num', models.IntegerField(default=0, verbose_name='题量')),
                ('single_score', models.IntegerField(default=1, verbose_name='分值')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civil.Category')),
            ],
            options={
                'verbose_name': '题型小类',
                'verbose_name_plural': '题型小类',
            },
        ),
    ]
