# Generated by Django 2.2.4 on 2019-08-09 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('civil', '0002_auto_20190809_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_num',
            field=models.PositiveIntegerField(default=1, verbose_name='题量'),
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_date', models.DateTimeField(verbose_name='日期')),
                ('practice_num', models.PositiveIntegerField(default=1, verbose_name='题量')),
                ('time_span', models.PositiveIntegerField(default=1, verbose_name='耗时')),
                ('error_num', models.IntegerField(default=0, verbose_name='错误')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civil.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '单项练习',
                'verbose_name_plural': '单项练习',
            },
        ),
    ]
