# Generated by Django 2.2.4 on 2019-08-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil', '0003_auto_20190809_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='error_num',
            field=models.PositiveIntegerField(default=0, verbose_name='错误'),
        ),
    ]
