# Generated by Django 2.2.4 on 2019-08-09 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('civil', '0004_auto_20190809_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='practice_date',
            field=models.DateTimeField(verbose_name='做题日期'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='做题人'),
        ),
        migrations.CreateModel(
            name='PracticeStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civil.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='做题人')),
            ],
            options={
                'verbose_name': '单项练习统计',
                'verbose_name_plural': '单项练习统计',
            },
        ),
    ]
